services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_AUTH_PROVIDER_1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      ZOOKEEPER_REQUIRE_CLIENT_AUTH_SCHEME: sasl
      ZOOKEEPER_JAAS_LOGIN_RENEW: 3600000
    ports:
      - "2181:2181"
    volumes:
      - ./auth/jaas/zookeeper_jaas.conf:/etc/kafka/zookeeper_jaas.conf
    command: >
      bash -c "export KAFKA_OPTS='-Djava.security.auth.login.config=/etc/kafka/zookeeper_jaas.conf' && /etc/confluent/docker/run"
    networks:
    - microservices-network


  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: gepg-kafka
    ports:
      - 9099:9099  # Exposes to host
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9099
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka:9099
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # SASL Authentication 
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      # Per-listener SASL config
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      #authorization
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: "User:anuary"
    depends_on:
      - zookeeper
    volumes:
      - ./auth/jaas/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      # - ./auth/libs/kafka-authorizer-3.3.1.jar:/usr/share/java/kafka/libs/kafka-authorizer-3.3.1.jar
      - ./auth/acls/client.properties:/etc/kafka/client.properties
    networks:
    - microservices-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: gepg-kafka-ui
    ports:
      - 8082:8082
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9099
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="readonly" password="readonly123";
 # ðŸ‘‡ BASIC AUTH USERS (format: user:pass,admin:admin123)
      KAFKA_UI_AUTH_TYPE: BASIC
      KAFKA_UI_AUTH_BASIC_USERS: "anuary:Vamos123!,readonly:readonly123"
      KAFKA_UI_DISABLE_LOGIN_FORM: "false"
    networks:
    - microservices-network

  config-service:
    build: ./config-service
    container_name: config-service
    volumes:
      - ./config-service/src:/app/src  # Mount your source code for real-time syncing
      - ./config-service/src/pom.xml:/app/pom.xml  # Mount your source code for real-time syncing
      - ~/.m2:/root/.m2    
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Dspring.devtools.restart.enabled=true  # Enable devtools
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - kafka
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  kafka_data: